// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.1
// source: pkg/collection/collection.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CollectionServiceClient is the client API for CollectionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CollectionServiceClient interface {
	GetByUserId(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*BasicResponse, error)
	GetByUserIdKind(ctx context.Context, in *KindRequest, opts ...grpc.CallOption) (*BasicResponse, error)
	GetByUserIdKindId(ctx context.Context, in *KindIdRequest, opts ...grpc.CallOption) (*KindIdResponse, error)
	AddToFavorite(ctx context.Context, in *FavoriteData, opts ...grpc.CallOption) (*AddToFavoriteResponse, error)
	RemoveFavorite(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
}

type collectionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCollectionServiceClient(cc grpc.ClientConnInterface) CollectionServiceClient {
	return &collectionServiceClient{cc}
}

func (c *collectionServiceClient) GetByUserId(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*BasicResponse, error) {
	out := new(BasicResponse)
	err := c.cc.Invoke(ctx, "/collection.CollectionService/GetByUserId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectionServiceClient) GetByUserIdKind(ctx context.Context, in *KindRequest, opts ...grpc.CallOption) (*BasicResponse, error) {
	out := new(BasicResponse)
	err := c.cc.Invoke(ctx, "/collection.CollectionService/GetByUserIdKind", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectionServiceClient) GetByUserIdKindId(ctx context.Context, in *KindIdRequest, opts ...grpc.CallOption) (*KindIdResponse, error) {
	out := new(KindIdResponse)
	err := c.cc.Invoke(ctx, "/collection.CollectionService/GetByUserIdKindId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectionServiceClient) AddToFavorite(ctx context.Context, in *FavoriteData, opts ...grpc.CallOption) (*AddToFavoriteResponse, error) {
	out := new(AddToFavoriteResponse)
	err := c.cc.Invoke(ctx, "/collection.CollectionService/AddToFavorite", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectionServiceClient) RemoveFavorite(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/collection.CollectionService/RemoveFavorite", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CollectionServiceServer is the server API for CollectionService service.
// All implementations must embed UnimplementedCollectionServiceServer
// for forward compatibility
type CollectionServiceServer interface {
	GetByUserId(context.Context, *IdRequest) (*BasicResponse, error)
	GetByUserIdKind(context.Context, *KindRequest) (*BasicResponse, error)
	GetByUserIdKindId(context.Context, *KindIdRequest) (*KindIdResponse, error)
	AddToFavorite(context.Context, *FavoriteData) (*AddToFavoriteResponse, error)
	RemoveFavorite(context.Context, *DeleteRequest) (*DeleteResponse, error)
	mustEmbedUnimplementedCollectionServiceServer()
}

// UnimplementedCollectionServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCollectionServiceServer struct {
}

func (UnimplementedCollectionServiceServer) GetByUserId(context.Context, *IdRequest) (*BasicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByUserId not implemented")
}
func (UnimplementedCollectionServiceServer) GetByUserIdKind(context.Context, *KindRequest) (*BasicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByUserIdKind not implemented")
}
func (UnimplementedCollectionServiceServer) GetByUserIdKindId(context.Context, *KindIdRequest) (*KindIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByUserIdKindId not implemented")
}
func (UnimplementedCollectionServiceServer) AddToFavorite(context.Context, *FavoriteData) (*AddToFavoriteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddToFavorite not implemented")
}
func (UnimplementedCollectionServiceServer) RemoveFavorite(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveFavorite not implemented")
}
func (UnimplementedCollectionServiceServer) mustEmbedUnimplementedCollectionServiceServer() {}

// UnsafeCollectionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CollectionServiceServer will
// result in compilation errors.
type UnsafeCollectionServiceServer interface {
	mustEmbedUnimplementedCollectionServiceServer()
}

func RegisterCollectionServiceServer(s grpc.ServiceRegistrar, srv CollectionServiceServer) {
	s.RegisterService(&CollectionService_ServiceDesc, srv)
}

func _CollectionService_GetByUserId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectionServiceServer).GetByUserId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/collection.CollectionService/GetByUserId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectionServiceServer).GetByUserId(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectionService_GetByUserIdKind_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectionServiceServer).GetByUserIdKind(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/collection.CollectionService/GetByUserIdKind",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectionServiceServer).GetByUserIdKind(ctx, req.(*KindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectionService_GetByUserIdKindId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KindIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectionServiceServer).GetByUserIdKindId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/collection.CollectionService/GetByUserIdKindId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectionServiceServer).GetByUserIdKindId(ctx, req.(*KindIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectionService_AddToFavorite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FavoriteData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectionServiceServer).AddToFavorite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/collection.CollectionService/AddToFavorite",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectionServiceServer).AddToFavorite(ctx, req.(*FavoriteData))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollectionService_RemoveFavorite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectionServiceServer).RemoveFavorite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/collection.CollectionService/RemoveFavorite",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectionServiceServer).RemoveFavorite(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CollectionService_ServiceDesc is the grpc.ServiceDesc for CollectionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CollectionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "collection.CollectionService",
	HandlerType: (*CollectionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetByUserId",
			Handler:    _CollectionService_GetByUserId_Handler,
		},
		{
			MethodName: "GetByUserIdKind",
			Handler:    _CollectionService_GetByUserIdKind_Handler,
		},
		{
			MethodName: "GetByUserIdKindId",
			Handler:    _CollectionService_GetByUserIdKindId_Handler,
		},
		{
			MethodName: "AddToFavorite",
			Handler:    _CollectionService_AddToFavorite_Handler,
		},
		{
			MethodName: "RemoveFavorite",
			Handler:    _CollectionService_RemoveFavorite_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/collection/collection.proto",
}
